import type { CommitFeed, CommitFeedEntry } from '../../../shared/types'

function CommitEntry({ entry }: { entry: CommitFeedEntry }): JSX.Element {
  const commitUrl = entry.remoteUrl ? `${entry.remoteUrl}/commit/${entry.hash}` : null
  const showOriginal = entry.summary !== entry.message && entry.summary.length > 0

  return (
    <div className="feed-entry">
      <div className="feed-entry-header">
        <span className="feed-repo-badge" title={entry.repoPath}>
          {entry.repoName}
        </span>
        <span className="feed-time">{entry.relative}</span>
      </div>

      <p className="feed-summary">{entry.summary || entry.message}</p>

      {showOriginal && (
        <p className="feed-original" title="Original commit message">
          {entry.message}
        </p>
      )}

      <div className="feed-meta">
        <span className="feed-author">{entry.author.split(' ')[0]}</span>
        {commitUrl ? (
          <a href={commitUrl} target="_blank" rel="noreferrer" className="feed-hash">
            {entry.hash.slice(0, 7)}
          </a>
        ) : (
          <span className="feed-hash">{entry.hash.slice(0, 7)}</span>
        )}
      </div>
    </div>
  )
}

interface Props {
  open: boolean
  feed: CommitFeed | null
  loading: boolean
  onClose: () => void
}

export default function CommitFeedPanel({ open, feed, loading, onClose }: Props): JSX.Element {
  return (
    <div className={`feed-panel${open ? ' feed-panel--open' : ''}`} aria-hidden={!open}>
      <div className="feed-header">
        <div className="feed-header-left">
          <span className="feed-title">Activity Feed</span>
          {feed?.aiAvailable && (
            <span className="feed-ai-badge" title={`Summaries powered by ${feed.aiModel} via ollama`}>
              AI
            </span>
          )}
          {feed && !feed.aiAvailable && (
            <span className="feed-no-ai-badge" title="Install ollama for AI summaries">
              raw
            </span>
          )}
        </div>
        <button className="feed-close icon-btn" onClick={onClose} title="Close activity feed">
          ✕
        </button>
      </div>

      <div className="feed-body">
        {loading && (
          <div className="feed-loading">
            <span className="feed-dot" />
            <span className="feed-dot" />
            <span className="feed-dot" />
          </div>
        )}

        {!loading && (!feed || feed.entries.length === 0) && (
          <div className="feed-empty">No recent commits found.</div>
        )}

        {!loading && feed && feed.entries.length > 0 && (
          <>
            {feed.aiAvailable && (
              <div className="feed-ai-notice">
                Summaries generated by <strong>{feed.aiModel}</strong>
              </div>
            )}
            <div className="feed-entries">
              {feed.entries.map((entry) => (
                <CommitEntry key={`${entry.repoPath}-${entry.hash}`} entry={entry} />
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  )
}
