import { useCallback, useEffect, useState } from 'react'
import type { CommitFeed, CommitFeedEntry } from '../../../shared/types'

function CommitEntry({ entry }: { entry: CommitFeedEntry }): JSX.Element {
  const commitUrl = entry.remoteUrl ? `${entry.remoteUrl}/commit/${entry.hash}` : null
  const showOriginal = entry.summary !== entry.message && entry.summary.length > 0

  return (
    <div className="feed-entry">
      <div className="feed-entry-header">
        <span className="feed-repo-badge" title={entry.repoPath}>
          {entry.repoName}
        </span>
        <span className="feed-time">{entry.relative}</span>
      </div>

      <p className="feed-summary">{entry.summary || entry.message}</p>

      {showOriginal && (
        <p className="feed-original" title="Original commit message">
          {entry.message}
        </p>
      )}

      <div className="feed-meta">
        <span className="feed-author">{entry.author.split(' ')[0]}</span>
        {commitUrl ? (
          <a href={commitUrl} target="_blank" rel="noreferrer" className="feed-hash">
            {entry.hash.slice(0, 7)}
          </a>
        ) : (
          <span className="feed-hash">{entry.hash.slice(0, 7)}</span>
        )}
      </div>
    </div>
  )
}

/** Standalone activity feed rendered inside its own docked window. Fetches and
 *  polls independently of the main command-center window. */
export default function FeedWindow(): JSX.Element {
  const [feed, setFeed] = useState<CommitFeed | null>(null)
  const [loading, setLoading] = useState(true)

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const repos = await window.api.listRepos()
      setFeed(await window.api.getCommitFeed(repos))
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    load()
    // Refresh every 20s while visible so AI summaries land as ollama finishes,
    // and refresh immediately whenever the window is re-shown. Skip work while
    // the window is hidden — the OS reports it via the Page Visibility API.
    const poll = window.setInterval(() => {
      if (document.visibilityState === 'visible') load()
    }, 20000)
    const onVisible = (): void => {
      if (document.visibilityState === 'visible') load()
    }
    document.addEventListener('visibilitychange', onVisible)
    return () => {
      window.clearInterval(poll)
      document.removeEventListener('visibilitychange', onVisible)
    }
  }, [load])

  return (
    <div className="feed-window">
      <div className="feed-header">
        <div className="feed-header-left">
          <span className="feed-title">Activity Feed</span>
          {feed?.aiAvailable && (
            <span
              className="feed-ai-badge"
              title={`Summaries powered by ${feed.aiModel} via ollama`}
            >
              AI
            </span>
          )}
          {feed && !feed.aiAvailable && (
            <span className="feed-no-ai-badge" title="Install ollama for AI summaries">
              raw
            </span>
          )}
        </div>
      </div>

      <div className="feed-body">
        {loading && !feed && (
          <div className="feed-loading">
            <span className="feed-dot" />
            <span className="feed-dot" />
            <span className="feed-dot" />
          </div>
        )}

        {!loading && (!feed || feed.entries.length === 0) && (
          <div className="feed-empty">No recent commits found.</div>
        )}

        {feed && feed.entries.length > 0 && (
          <>
            {feed.aiAvailable && (
              <div className="feed-ai-notice">
                Summaries generated by <strong>{feed.aiModel}</strong>
              </div>
            )}
            <div className="feed-entries">
              {feed.entries.map((entry) => (
                <CommitEntry key={`${entry.repoPath}-${entry.hash}`} entry={entry} />
              ))}
            </div>
          </>
        )}
      </div>
    </div>
  )
}
